# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'LSCellFactory' do

#SDWebImage
platform :ios, '6.1'
pod 'SDWebImage', '~>3.7'

#MJRefresh
pod 'MJRefresh'

end

